- name: Azure Arc 지원 Kubernetes 설명서
  href: index.yml
- name: 개요
  items:
    - name: Arc 지원 Kubernetes 정보
      href: overview.md
- name: 방법 가이드
  items:
    - name: Azure Arc에 연결
      items:
        - name: 클러스터 연결
          href: connect-cluster.md
        - name: 서비스 사용자 온보딩
          href: create-onboarding-service-principal.md
    - name: 관리
      items:
        - name: GitOps를 사용하여 구성 배포
          href: use-gitops-connected-cluster.md
        - name: GitOps를 사용하여 Helm 차트 배포
          href: use-gitops-with-helm.md
        - name: Azure Policy를 사용하여 GitOps 적용
          href: use-azure-policy.md
        - name: 컨테이너용 Azure Monitor를 사용하여 모니터링
          href: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Azure Policy를 사용한 허용 제어 정책
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: IoT 워크로드 배포
          href: deploy-azure-iot-edge-workloads.md
    - name: 문제 해결
      href: Troubleshooting.md
- name: 참고
  items:
    - name: Azure Policy 기본 제공 기능
      displayName: 'samples, policies, definitions'
      href: policy-reference.md